import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import NextAuthProvider from "@/Providers/NextAuthProvider/NextAuthProvider";
import { auth } from "@/auth";
import ReactQueryProviders from "@/Providers/ReactQueryProvider/ReactProvider";
import NextTopLoader from 'nextjs-toploader';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "TrendiQ",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div>
          <NextAuthProvider session={session}>
            <ReactQueryProviders>
            <NextTopLoader  color="#FF0000" height={3} showSpinner={false}/>
              <div>
                <Toaster  theme="light"/>
              </div>
              <div>{children}</div>
            </ReactQueryProviders>
          </NextAuthProvider>
        </div>
      </body>
    </html>
  );
}
