import type { Metadata } from "next";
import {Open_Sans} from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import NextAuthProvider from "@/Providers/NextAuthProvider/NextAuthProvider";
import { auth } from "@/auth";
import ReactQueryProviders from "@/Providers/ReactQueryProvider/ReactProvider";
import NextTopLoader from 'nextjs-toploader';

const poppins = Open_Sans({
  subsets: ["latin"],
  display:"swap"
})

export const metadata: Metadata = {
  title: "TrendiQ",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        <div>
          <NextAuthProvider session={session}>
            <ReactQueryProviders>
            <NextTopLoader  color="#FF0000" height={3} showSpinner={false}/>
              <div>
                <Toaster  theme="light"/>
              </div>
              <div>{children}</div>
            </ReactQueryProviders>
          </NextAuthProvider>
        </div>
      </body>
    </html>
  );
}
